services:
 db:
  container_name: postgres
  image: postgres
  restart: always
  environment:
   POSTGRES_DB: budget_dev
   POSTGRES_USER: test_user
   POSTGRES_PASSWORD: 1234
  ports:
   - 5432:5432
  volumes:
   - postgres-data:/var/lib/postgresql/data
 adminer:
  image: adminer
  restart: always
  ports: 
   - 8080:8080
volumes:
 postgres-data: